let files=[],token=sessionStorage.getItem("adminToken")||"";const $=x=>document.getElementById(x);
async function load(){files=await (await fetch("/api/files")).json();render()}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function fmt(n){if(n<1024)return n+" B";if(n<1048576)return(n/1024).toFixed(1)+" KB";return(n/1048576).toFixed(1)+" MB"}
function render(){let q=$("search").value.toLowerCase(),sel=$("folderFilter").value;let ff=files.filter(f=>(!q||(`${f.name} ${f.folder}`).toLowerCase().includes(q))&&(!sel||f.folder===sel));let folders=[...new Set(files.map(f=>f.folder||"General"))].sort();$("folderFilter").innerHTML='<option value="">All folders</option>'+folders.map(x=>`<option ${x===sel?"selected":""} value="${esc(x)}">${esc(x)}</option>`).join("");$("fileCount").textContent=files.length;$("folderCount").textContent=folders.length;$("totalSize").textContent=fmt(files.reduce((a,b)=>a+b.size,0));let g={};ff.forEach(f=>(g[f.folder||"General"]??=[]).push(f));$("folders").innerHTML=Object.keys(g).length?Object.entries(g).map(([folder,list])=>`<article class="folder"><div class="folderTitle"><span class="folderIcon">📁</span><div><h3>${esc(folder)}</h3><span class="count">${list.length} file${list.length!==1?"s":""}</span></div></div>${list.map(f=>`<div class="file"><a href="/api/download/${f.id}" title="${esc(f.name)}">📄 ${esc(f.name)}</a><span class="download">↓ ${fmt(f.size)}</span></div>`).join("")}</article>`).join(""):'<div class="empty"><h3>No resources found</h3><p>Try another search or folder.</p></div>'}
$("search").oninput=render;$("folderFilter").onchange=render;$("adminBtn").onclick=()=>{$("modal").classList.remove("hidden");if(token)panel()};function closeModal(){$("modal").classList.add("hidden")}
async function login(){let r=await fetch("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:$("password").value})});if(!r.ok){$("loginError").textContent="Wrong password.";return}let d=await r.json();token=d.token;sessionStorage.setItem("adminToken",token);panel()}
async function panel(){$("loginView").classList.add("hidden");$("panelView").classList.remove("hidden");adminList()}
async function uploadFiles(){let fs=[...$("files").files];if(!fs.length){$("uploadStatus").textContent="Select a folder or files first.";return}let form=new FormData();form.append("folder",$("folderName").value.trim());fs.forEach(f=>form.append("files",f,f.webkitRelativePath||f.name));$("uploadStatus").textContent="Uploading...";$("progress").classList.remove("hidden");$("progress").firstElementChild.style.width="30%";let r=await fetch("/api/upload",{method:"POST",headers:{"x-admin-token":token},body:form});let d=await r.json();if(!r.ok){$("uploadStatus").textContent=d.error||"Upload failed.";return}$("progress").firstElementChild.style.width="100%";$("uploadStatus").textContent=`Uploaded ${d.added} file(s) successfully.`;$("files").value="";await load();adminList();toast("Upload complete")}
async function adminList(){$("adminFiles").innerHTML=files.map(f=>`<div class="adminItem"><span>${esc(f.folder)} / ${esc(f.name)}</span><button class="danger" onclick="del('${f.id}')">Delete</button></div>`).join("")||"<p>No files yet.</p>"}
async function del(id){if(!confirm("Delete this file?"))return;let r=await fetch("/api/files/"+id,{method:"DELETE",headers:{"x-admin-token":token}});if(r.ok){await load();adminList();toast("File deleted")}}
function toast(t){$("toast").textContent=t;$("toast").style.display="block";setTimeout(()=>$("toast").style.display="none",2200)}
load();